map1: main.o kdtree.o BusinessData.o FileOperations.o
		gcc -Wall -o map1  main.o kdtree.o BusinessData.o FileOperations.o -lm

main.o: main.c
		gcc -c -Wall main.c

kdtree.o: kdtree.c
		gcc -c -Wall kdtree.c

BusinessData.o: BusinessData.c
		gcc -c -Wall BusinessData.c

FileOperations.o: FileOperations.c
		gcc -c -Wall FileOperations.c

