map2: map2.o kdtree.o BusinessData.o FileOperations.o
		gcc -Wall -o map2  map2.o kdtree.o BusinessData.o FileOperations.o -lm

map2.o: map2.c
		gcc -c -Wall map2.c

kdtree.o: kdtree.c
		gcc -c -Wall kdtree.c

BusinessData.o: BusinessData.c
		gcc -c -Wall BusinessData.c

FileOperations.o: FileOperations.c
		gcc -c -Wall FileOperations.c

